### ISSUE TITLE
Developing video stream processing feature

### ISSUE THREAD

**Issue by haloxhanner** [ahmetozlu/object_detection_chooch#1]
I used your project for one of my object counting project and it works perfect for object counting on single image. Its speed and detection accuracy amazing! I have not heard chooch api far so I think it is a new tech in this field! I am planning to create an account and use this awesome api with my own api key in my projects but I really wonder it has capabilities for producing results in video stream processing.

I am not a python proıgramming master so I could not modify your codes to process video stream for my project so do you have any plan to extend your this perfect project to process video as well?

Thanks and regards...

**Comment by ahmetozlu** [comment]
[CHOOCH AI API](https://chooch.ai/api/#general-recognition-api) also provides video processing for object detection. However, I suggest that input video should read frame by frame using OpenCV and then each frame can be processed a single image using CHOOCH AI API so you can reach real time object detector. This would be better approach to process videos in terms of processing speed.
